version: 2.0

jobs:
  build:
    docker:
      - image: circleci/golang:1.11
    working_directory: ~/voyex
    steps:
      - checkout
      - run: ./ci/build.sh
  release:
    docker:
      - image: circleci/golang:1.11
    working_directory: ~/voyex
    steps:
      - checkout
      - run: ./ci/release.sh

workflows:
  version: 2

  build:
    jobs:
      - build

  release:
    jobs:
      - build
      - release:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/
