version: 2.0

jobs:
  release:
    docker:
      - image: circleci/golang:1.11
    working_directory: ~/voyex
    steps:
      - checkout
      - run: ./ci/release.sh

workflows:
  version: 2
  release:
    jobs:
      - release:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/
